= vsp(1)
:doctype: manpage
:manmanual: xsys35c manual
:mansource: xsys35c {xsys35c-version}

== Name
vsp, pms, qnt - utilities for VSP, PMS, and QNT images

== Synopsis
[verse]
*vsp* [_options_] _file_...
*pms* [_options_] _file_...
*qnt* [_options_] _file_...

== Description
By default, the *vsp*, *pms*, and *qnt* commands convert VSP, PMS, and QNT
image files to PNG format, respectively. If the `-e` option is specified,
these commands convert PNG files back to VSP, PMS, or QNT format.

The output filename will be the same as the input filename, but with the
extension changed to `.png`, `.vsp`, `.pms`, or `.qnt`, depending on the
destination format.

== Options
*-e, --encode*::
  Encode PNG file(s) to VSP, PMS, or QNT format.

*-h, --help*::
  Display a help message about the command and exit.

*-i, --info*::
  Print information about the input files, such as image dimensions and default
  display positions. If this option is given, no image format conversion will
  be performed.

*-o, --output*=_filename_::
  Write the output to _filename_ (only valid if a single input file is
  specified).

*-p, --position*=_x_,_y_::
  When encoding, set the default display position of the image to (_x_, _y_).
  If omitted, the values in the `oFFs` chunk of the input PNG file will be
  used.

*-v, --version*::
  Display the version number and exit.

*--palette-bank*=_bank_::
  (*vsp*) When encoding, set the palette bank to _bank_. The palette bank is a
  number between 0 and 15 that specifies which area of the system's 256-color
  palette this 16-color image should use. For example, an image with a palette
  bank of 15 uses the system palette ranging from 240 to 255.

*--palette-mask*=_mask_::
  (*pms*) When encoding, set the palette mask to _mask_. The palette mask is a
  16-bit integer that specifies which area of this image's 256-color palette is
  effective. For example, an image with a palette mask of 0x7fff will overwrite
  system palette values from 0 to 239.

*--system2*::
  (*pms*) Read/write in the legacy PMS format, which was used in older
  (System2 - System3) AliceSoft games.

== Examples

The following command converts _image.vsp_ to _image.png_:

  vsp image.vsp

The following command converts _image.png_ to _image.vsp_ and sets the default
position to (80, 50):

  vsp -e image.png -p 80,50

To view information for all PMS files in the current directory:

  pms -i *.pms
