= xsys35dc(1)
:doctype: manpage
:manmanual: xsys35c manual
:mansource: xsys35c

== Name
xsys35dc - System 3.x decompiler

== Synopsis
*xsys35dc* [_options_] _aldfile_... [_system39.ain_]

== Description
`xsys35dc` is a decompiler for AliceSoft's System 3.x game engine. It processes
a scenario file (usually having the suffix `SA.ALD`) and, optionally, a
`System39.ain` file (for System 3.9 games). It then generates source files that
can be compiled using xref:xsys35c.adoc[*xsys35c(1)*] or the official System
3.x SDK.

== Options
*-a, --address*::
  Prefix each line with its address.

*-d, --aindump*::
  Output the contents of the _system39.ain_ file to standard output in JSON
  format. Decompilation will not be executed.

*-E, --encoding*=_enc_::
  Specify the text encoding for output files. Possible values are `sjis` and
  `utf8` (default).

*-h, --help*::
  Display a help message for `xsys35dc` and exit.

*-o, --outdir*=_directory_::
  Generate output files in the specified _directory_. By default, output files
  are created in the current directory.

*-s, --seq*::
  Generate ADV files with sequential filenames (`0.adv`, `1.adv`, ...) instead
  of using their original names.

*-V, --verbose*::
  Enable verbose output.

*-v, --version*::
  Display the version number of `xsys35dc` and exit.

== Output
In addition to generating System 3.x source files (`*.ADV`), `xsys35dc` also
creates a `xsys35c.cfg` configuration file for use with
xref:xsys35c.adoc[*xsys35c(1)*]. With this, the original scenario file can be
recompiled using the following command:

  xsys35c -p xsys35c.cfg

If you wish to use the official System 3.x SDK, specify the generated
`xsys35dc.hed` file in the `DIR.HED` file within your project directory.

== See also
xref:xsys35c.adoc[*xsys35c(1)*], xref:ald.adoc[*ald(1)*]
