= xsys35dc(1)
:doctype: manpage
:manmanual: xsys35c manual
:mansource: xsys35c

== Name
xsys35dc - System 3.x decompiler

== Synopsis
*xsys35dc* [_options_] _aldfile_... [_system39.ain_]

== Description
`xsys35dc` is a decompiler for AliceSoft's System 3.x game engine. It reads a
scenario file (usually with the suffix `SA.ALD`) and optionally a `System39.ain`
file (for System 3.9 games), and generates source files that can be compiled
with xref:xsys35c.adoc[*xsys35c(1)*] or the official System 3.x SDK.

== Options
*-a, --address*::
  Prefix each line with address.

*-d, --aindump*::
  Dump the contents of _system39.ain_ file to standard output, in JSON format.
  Decompilation will not be performed.

*-E, --encoding*=_enc_::
  Specify text encoding of output files. Possible values are `sjis` and `utf8`
  (default).

*-h, --help*::
  Display help message about `xsys35dc` and exit.

*-o, --outdir*=_directory_::
  Generate output files under _directory_. By default, output files are
  generated in current directory.

*-s, --seq*::
  Output ADV files with sequential filenames (`0.adv`, `1.adv`, ...) instead of
  their original names.

*-V, --verbose*::
  Turn on verbose output.

*-v, --version*::
  Display the `xsys35dc` version number and exit.

== Output
In addition to System 3.x source files (`{asterisk}.ADV`), `xsys35dc` also generates
`xsys35c.cfg` file which is a configuration file for
xref:xsys35c.adoc[*xsys35c(1)*]. Using this, the original scenario file can be
reconstructed by this command:

  xsys35c -p xsys35c.cfg

If you want to use the official System 3.x SDK, specify the generated
`xsys35dc.hed` file in the `DIR.HED` file of your project directory.

== Bugs
`xsys35dc` cannot decompile scenario files compiled with
xref:unicode.adoc[Unicode Mode].

== See also
xref:xsys35c.adoc[*xsys35c(1)*], xref:ald.adoc[*ald(1)*]
