name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Deps
      run: |
        sudo apt update
        sudo apt install meson libpng-dev

    - name: Build
      run: |
        meson build
        ninja -C build

    - name: test
      run: ninja -C build test
